#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
RedSand Antivirus GUI v8.0 - Modern Professional Interface
Исправленная логика сканирования без ложных срабатываний
Современный дизайн на PyQt6
"""

import sys
import os
import hashlib
import json
import re
import time
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List, Tuple
from threading import Thread
import configparser

try:
    import magic
except ImportError:
    magic = None

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, QLabel,
    QPushButton, QProgressBar, QFileDialog, QGroupBox, QSplitter, 
    QTabWidget, QMessageBox, QCheckBox, QSpinBox, QComboBox, 
    QTableWidget, QTableWidgetItem, QHeaderView, QDialog, 
    QDialogButtonBox, QFormLayout, QPlainTextEdit, QFrame, QScrollArea
)
from PyQt6.QtCore import (
    Qt, QTimer, pyqtSignal, QObject, QThread, QSize, QPropertyAnimation, QEasingCurve
)
from PyQt6.QtGui import (
    QFont, QColor, QPalette, QIcon, QAction, QMenu
)

# ============================================================================
# АНАЛИЗАТОР УГРОЗ (ИСПРАВЛЕННАЯ ЛОГИКА)
# ============================================================================

class ThreatAnalyzer:
    """
    Реальный анализатор угроз с защитой от ложных срабатываний.
    """
    
    # Опасные расширения (исполняемые файлы)
    DANGEROUS_EXTENSIONS = {'.exe', '.dll', '.sys', '.bat', '.cmd', '.ps1', '.vbs', '.js', '.msi', '.scr'}
    
    # Подозрительные расширения (скрипты, документы с макросами)
    SUSPICIOUS_EXTENSIONS = {'.py', '.pyw', '.docm', '.xlsm', '.pptm', '.hta', '.wsf'}
    
    # Критические API для Windows исполняемых файлов
    CRITICAL_APIS = [
        'VirtualAllocEx', 'WriteProcessMemory', 'CreateRemoteThread',
        'NtUnmapViewOfSection', 'SetWindowsHookEx', 'GetAsyncKeyState',
        'URLDownloadToFile', 'WinExec', 'ShellExecute', 'CryptEncrypt',
        'RegSetValueEx', 'CreateService', 'OpenProcess'
    ]
    
    # Индикаторы конкретных угроз
    THREAT_INDICATORS = {
        'RANSOMWARE': [b'your files are encrypted', b'bitcoin', b'ransom', b'decrypt', b'wallet'],
        'STEALER': [b'steal', b'password', b'cookie', b'token', b'credential', b'keylog'],
        'BACKDOOR': [b'backdoor', b'reverse shell', b'c2 server', b'command and control', b'beacon'],
        'TROJAN': [b'trojan', b'dropper', b'downloader', b'payload'],
        'MINER': [b'miner', b'stratum', b'coinhive', b'monero', b'xmr'],
        'ROOTKIT': [b'rootkit', b'hide process', b'hook ssdt', b'kernel mode'],
        'WORM': [b'worm', b'spread', b'network share', b'replication'],
        'ADWARE': [b'adware', b'popup', b'banner', b'redirect'],
        'SPYWARE': [b'spy', b'screenshot', b'microphone', b'webcam', b'surveillance']
    }
    
    # Белый список безопасных строк (снижает риск)
    SAFE_STRINGS = [
        b'copyright', b'license', b'mit', b'apache', b'gnu', b'version',
        b'author', b'email', b'description', b'python', b'import',
        b'def ', b'class ', b'print(', b'if __name__', b'# -*- coding',
        b'microsoft', b'corporation', b'all rights reserved',
        b'generated by', b'compiler', b'build', b'source'
    ]

    def __init__(self):
        self.results = []
        self.threats_found = []
        self.safe_score = 0
        self.danger_score = 0

    def analyze_file(self, file_path: str) -> Dict[str, Any]:
        """Полный анализ файла."""
        self.results = []
        self.threats_found = []
        self.safe_score = 0
        self.danger_score = 0
        
        path = Path(file_path)
        
        if not path.exists():
            return {"error": "File not found"}
        
        # 1. Базовая информация
        file_size = path.stat().st_size
        file_ext = path.suffix.lower()
        
        self._log_info(f"Анализ файла: {path.name}")
        self._log_info(f"Размер: {file_size} байт")
        self._log_info(f"Расширение: {file_ext}")
        
        # 2. Проверка расширений
        self._check_extension(file_ext)
        
        # 3. Чтение содержимого (первые 1MB для скорости)
        try:
            with open(file_path, 'rb') as f:
                content = f.read(1024 * 1024)
            
            # 4. Проверка Magic Bytes
            self._check_magic_bytes(content, file_ext)
            
            # 5. Поиск опасных строк и API
            self._check_content(content, file_ext)
            
            # 6. Оценка безопасности (белый список)
            self._check_safe_strings(content)
            
        except Exception as e:
            self._log_error(f"Ошибка чтения файла: {str(e)}")
        
        # 7. Финальный вердикт
        verdict = self._calculate_verdict()
        
        return {
            "file": str(path),
            "size": file_size,
            "extension": file_ext,
            "threats": self.threats_found,
            "threat_count": len(self.threats_found),
            "verdict": verdict["verdict"],
            "risk_level": verdict["risk"],
            "details": self.results
        }

    def _log_info(self, msg: str):
        self.results.append({"type": "INFO", "message": msg, "severity": "low"})

    def _log_warning(self, msg: str):
        self.results.append({"type": "WARNING", "message": msg, "severity": "medium"})
        self.danger_score += 5

    def _log_danger(self, msg: str, threat_type: str = None):
        # Проверяем, нет ли уже такой угрозы (защита от дублей)
        if threat_type:
            for t in self.threats_found:
                if t.get('name') == threat_type:
                    return  # Уже есть такая угроза
        
        self.results.append({"type": "DANGER", "message": msg, "severity": "high"})
        self.danger_score += 20
        if threat_type:
            self.threats_found.append({"name": threat_type, "reason": msg})

    def _check_extension(self, ext: str):
        """Проверка расширения файла."""
        if ext in self.DANGEROUS_EXTENSIONS:
            self._log_warning(f"Подозрительное расширение: {ext} (исполняемый файл)")
        elif ext in self.SUSPICIOUS_EXTENSIONS:
            # Для .py это нормально, просто предупреждение
            if ext == '.py':
                self._log_info("Файл является Python скриптом. Требуется проверка кода.")
            else:
                self._log_warning(f"Расширение может содержать макросы: {ext}")

    def _check_magic_bytes(self, content: bytes, ext: str):
        """Проверка сигнатур файла."""
        if len(content) < 4:
            return
            
        # MZ заголовок (PE файл)
        if content[:2] == b'MZ':
            if ext != '.exe' and ext != '.dll':
                self._log_danger("Несоответствие расширения и содержимого (PE файл)", "MASQUERADE")
            else:
                self._log_info("Обнаружен PE формат (Windows Executable)")
        
        # ELF (Linux)
        elif content[:4] == b'\x7fELF':
            self._log_info("Обнаружен ELF формат (Linux Executable)")
            
        # PDF
        elif content[:4] == b'%PDF':
            self._log_info("Обнаружен PDF документ")
            
        # ZIP/Office
        elif content[:2] == b'PK':
            self._log_info("Обнаружен ZIP архив или Office документ")

    def _check_content(self, content: bytes, ext: str):
        """Поиск опасных паттернов."""
        
        # Ищем критические API только в бинарных файлах или если это скрипт
        # Но игнорируем импорты в Python коде, если это не обфускация
        if ext in ['.exe', '.dll', '.sys']:
            for api in self.CRITICAL_APIS:
                if api.encode() in content:
                    self._log_warning(f"Обнаружен опасный API: {api}")
        
        # Поиск индикаторов угроз
        for threat_type, indicators in self.THREAT_INDICATORS.items():
            matches = 0
            for indicator in indicators:
                if indicator in content.lower():
                    matches += 1
            
            # Угроза считается подтвержденной только при множественных совпадениях
            if matches >= 2:
                self._log_danger(f"Найдены индикаторы типа {threat_type} ({matches} совпадений)", threat_type)
            elif matches == 1:
                # Единичное совпадение - просто предупреждение, а не угроза
                self._log_warning(f"Возможный индикатор {threat_type} (требуется проверка)")

    def _check_safe_strings(self, content: bytes):
        """Проверка на признаки легитимного ПО."""
        content_lower = content.lower()
        safe_matches = 0
        
        for safe in self.SAFE_STRINGS:
            if safe in content_lower:
                safe_matches += 1
        
        if safe_matches > 3:
            self.safe_score += safe_matches * 10
            self._log_info(f"Найдено признаков легитимного ПО: {safe_matches}")

    def _calculate_verdict(self) -> Dict[str, str]:
        """Расчет финального вердикта."""
        # Если файл легитимный (много safe строк) и мало угроз
        if self.safe_score > 30 and self.danger_score < 20:
            return {"verdict": "CLEAN", "risk": "0%"}
        
        # Если найдены реальные угрозы
        if len(self.threats_found) > 0:
            risk = min(100, 20 + len(self.threats_found) * 15 + self.danger_score)
            return {"verdict": "MALICIOUS", "risk": f"{risk}%"}
        
        # Если есть подозрения, но нет явных угроз
        if self.danger_score > 15:
            return {"verdict": "SUSPICIOUS", "risk": f"{min(60, self.danger_score)}%"}
        
        return {"verdict": "CLEAN", "risk": "0%"}


# ============================================================================
# GUI ПРИЛОЖЕНИЕ
# ============================================================================

class RedSandGUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.analyzer = ThreatAnalyzer()
        self.current_file = None
        self.is_scanning = False
        
        # Настройки
        self.config = {
            'deep_scan': True,
            'heuristic': True,
            'language': 'ru'
        }
        
        self._init_ui()
        self._apply_styles()
        
    def _init_ui(self):
        """Инициализация интерфейса."""
        self.setWindowTitle("RedSand Antivirus v8.0")
        self.setMinimumSize(1000, 700)
        self.resize(1200, 800)
        
        # Центральная область
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QVBoxLayout(central_widget)
        main_layout.setSpacing(15)
        main_layout.setContentsMargins(20, 20, 20, 20)
        
        # Заголовок
        header_layout = QHBoxLayout()
        title_label = QLabel("🛡️ RedSand Antivirus")
        title_label.setFont(QFont("Segoe UI", 24, QFont.Weight.Bold))
        title_label.setStyleSheet("color: #ff4757; padding: 10px;")
        header_layout.addWidget(title_label)
        header_layout.addStretch()
        
        # Меню языков
        lang_menu = QComboBox()
        lang_menu.addItems(["Русский", "English"])
        lang_menu.currentIndexChanged.connect(self.change_language)
        lang_menu.setFixedWidth(120)
        header_layout.addWidget(lang_menu)
        
        main_layout.addLayout(header_layout)
        
        # Основная панель
        panel = QFrame()
        panel.setObjectName("MainPanel")
        panel_layout = QVBoxLayout(panel)
        
        # Выбор файла
        file_layout = QHBoxLayout()
        file_label = QLabel("Файл для проверки:")
        file_label.setFont(QFont("Segoe UI", 12))
        file_layout.addWidget(file_label)
        
        self.file_path_edit = QLineEdit()
        self.file_path_edit.setPlaceholderText("Выберите файл или перетащите сюда...")
        self.file_path_edit.setReadOnly(True)
        self.file_path_edit.setMinimumHeight(40)
        file_layout.addWidget(self.file_path_edit)
        
        browse_btn = QPushButton("📂 Обзор")
        browse_btn.clicked.connect(self.browse_file)
        browse_btn.setMinimumHeight(40)
        browse_btn.setMinimumWidth(100)
        file_layout.addWidget(browse_btn)
        
        panel_layout.addLayout(file_layout)
        
        # Кнопки управления
        btn_layout = QHBoxLayout()
        self.scan_btn = QPushButton("🚀 СКАНИРОВАТЬ")
        self.scan_btn.setFont(QFont("Segoe UI", 14, QFont.Weight.Bold))
        self.scan_btn.setMinimumHeight(50)
        self.scan_btn.clicked.connect(self.start_scan)
        btn_layout.addWidget(self.scan_btn)
        
        self.stop_btn = QPushButton("⏹ СТОП")
        self.stop_btn.setEnabled(False)
        self.stop_btn.setMinimumHeight(50)
        self.stop_btn.clicked.connect(self.stop_scan)
        btn_layout.addWidget(self.stop_btn)
        
        panel_layout.addLayout(btn_layout)
        
        # Прогресс
        progress_group = QGroupBox("Прогресс сканирования")
        progress_layout = QVBoxLayout(progress_group)
        
        self.progress_bar = QProgressBar()
        self.progress_bar.setMinimumHeight(25)
        self.progress_bar.setValue(0)
        progress_layout.addWidget(self.progress_bar)
        
        self.status_label = QLabel("Статус: Готов к работе")
        self.status_label.setFont(QFont("Consolas", 10))
        progress_layout.addWidget(self.status_label)
        
        panel_layout.addWidget(progress_group)
        
        main_layout.addWidget(panel)
        
        # Вкладки результатов
        self.tabs = QTabWidget()
        self.tabs.setMinimumHeight(300)
        
        # Вкладка логов
        self.log_view = QPlainTextEdit()
        self.log_view.setReadOnly(True)
        self.log_view.setFont(QFont("Consolas", 10))
        self.log_view.setStyleSheet("""
            QPlainTextEdit { 
                background-color: #1e1e1e; 
                color: #d4d4d4; 
                border: 1px solid #333;
                padding: 10px;
            }
        """)
        self.tabs.addTab(self.log_view, "📋 Журнал событий")
        
        # Вкладка результатов
        self.results_table = QTableWidget()
        self.results_table.setColumnCount(3)
        self.results_table.setHorizontalHeaderLabels(["Тип", "Сообщение", "Уровень"])
        self.results_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.results_table.setAlternatingRowColors(True)
        self.tabs.addTab(self.results_table, "📊 Результаты")
        
        main_layout.addWidget(self.tabs)
        
    def _apply_styles(self):
        """Применение современного стиля."""
        self.setStyleSheet("""
            QMainWindow {
                background-color: #121212;
                color: #ffffff;
            }
            QFrame#MainPanel {
                background-color: #1e1e1e;
                border-radius: 15px;
                padding: 20px;
            }
            QPushButton {
                background-color: #00d9ff;
                color: #000;
                border: none;
                border-radius: 8px;
                font-weight: bold;
                padding: 10px;
            }
            QPushButton:hover {
                background-color: #00b8d9;
            }
            QPushButton:disabled {
                background-color: #555;
                color: #888;
            }
            QPushButton#StopBtn {
                background-color: #ff4757;
            }
            QLineEdit {
                background-color: #2d2d2d;
                border: 1px solid #444;
                border-radius: 5px;
                padding: 8px;
                color: #fff;
            }
            QProgressBar {
                border: 1px solid #444;
                border-radius: 5px;
                text-align: center;
                background-color: #2d2d2d;
                color: white;
            }
            QProgressBar::chunk {
                background-color: #00d9ff;
                border-radius: 4px;
            }
            QTabWidget::pane {
                border: 1px solid #333;
                border-radius: 10px;
                background-color: #1e1e1e;
            }
            QTabBar::tab {
                background-color: #2d2d2d;
                color: #aaa;
                padding: 10px 20px;
                border-top-left-radius: 8px;
                border-top-right-radius: 8px;
                margin-right: 2px;
            }
            QTabBar::tab:selected {
                background-color: #1e1e1e;
                color: #00d9ff;
            }
            QTableWidget {
                background-color: #1e1e1e;
                color: #ddd;
                gridline-color: #333;
            }
            QTableWidget::item:selected {
                background-color: #00d9ff33;
            }
            QHeaderView::section {
                background-color: #2d2d2d;
                color: #fff;
                padding: 8px;
                border: none;
            }
            QGroupBox {
                font-weight: bold;
                color: #00d9ff;
                border: 1px solid #333;
                border-radius: 8px;
                margin-top: 10px;
                padding-top: 10px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px;
            }
            QComboBox {
                background-color: #2d2d2d;
                color: white;
                border: 1px solid #444;
                border-radius: 5px;
                padding: 5px;
            }
            QComboBox::drop-down {
                border: none;
                width: 20px;
            }
        """)

    def browse_file(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Выберите файл", "", "All Files (*)")
        if file_path:
            self.current_file = file_path
            self.file_path_edit.setText(file_path)
            self.log_message(f"[INFO] Выбран файл: {file_path}")
            
    def change_language(self, index):
        # Заглушка для переключения языка
        lang = "Русский" if index == 0 else "English"
        self.log_message(f"[INFO] Язык изменен на: {lang}")
        # Здесь должна быть полная реализация перевода
        
    def log_message(self, msg: str):
        timestamp = datetime.now().strftime("%H:%M:%S")
        self.log_view.appendPlainText(f"[{timestamp}] {msg}")
        self.log_view.verticalScrollBar().setValue(self.log_view.verticalScrollBar().maximum())
        
    def start_scan(self):
        if not self.current_file:
            QMessageBox.warning(self, "Ошибка", "Сначала выберите файл!")
            return
            
        self.is_scanning = True
        self.scan_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)
        self.progress_bar.setValue(0)
        self.results_table.setRowCount(0)
        self.log_view.clear()
        
        self.log_message("[INFO] Начало сканирования...")
        self.status_label.setText("Статус: Сканирование...")
        
        # Запуск в потоке
        self.thread = Thread(target=self.run_scan)
        self.thread.start()
        
        # Анимация прогресса
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_progress)
        self.timer.start(50)
        
    def run_scan(self):
        results = self.analyzer.analyze_file(self.current_file)
        
        # Обновление UI в главном потоке
        QTimer.singleShot(0, lambda: self.finish_scan(results))
        
    def update_progress(self):
        val = self.progress_bar.value()
        if val < 90:
            self.progress_bar.setValue(val + 5)
            
    def finish_scan(self, results):
        self.timer.stop()
        self.progress_bar.setValue(100)
        self.is_scanning = False
        self.scan_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        
        # Отображение результатов
        verdict = results.get('verdict', 'UNKNOWN')
        risk = results.get('risk_level', '0%')
        threats = results.get('threats', [])
        
        self.status_label.setText(f"Статус: Завершено. Вердикт: {verdict}")
        
        # Цвет вердикта
        color = "#2ed573" if verdict == "CLEAN" else ("#ffa502" if verdict == "SUSPICIOUS" else "#ff4757")
        self.status_label.setStyleSheet(f"font-weight: bold; color: {color}; font-size: 14px;")
        
        self.log_message(f"[RESULT] Вердикт: {verdict}, Риск: {risk}")
        self.log_message(f"[RESULT] Найдено угроз: {len(threats)}")
        
        # Заполнение таблицы
        details = results.get('details', [])
        self.results_table.setRowCount(len(details))
        
        for i, item in enumerate(details):
            type_item = QTableWidgetItem(item['type'])
            msg_item = QTableWidgetItem(item['message'])
            sev_item = QTableWidgetItem(item['severity'])
            
            # Цвета для типов
            if item['type'] == 'DANGER':
                type_item.setForeground(QColor("#ff4757"))
            elif item['type'] == 'WARNING':
                type_item.setForeground(QColor("#ffa502"))
            else:
                type_item.setForeground(QColor("#2ed573"))
                
            self.results_table.setItem(i, 0, type_item)
            self.results_table.setItem(i, 1, msg_item)
            self.results_table.setItem(i, 2, sev_item)
            
        # Финальное окно
        msg = f"Вердикт: {verdict}\nУровень риска: {risk}\nНайдено угроз: {len(threats)}\n\n"
        if threats:
            msg += "Обнаруженные угрозы:\n" + "\n".join([f"- {t['name']}: {t['reason']}" for t in threats])
        else:
            msg += "Детальных угроз не найдено. Файл считается безопасным."
            
        QMessageBox.information(self, "Результаты сканирования", msg)

    def stop_scan(self):
        self.is_scanning = False
        self.timer.stop()
        self.scan_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self.status_label.setText("Статус: Остановлено пользователем")
        self.log_message("[WARNING] Сканирование остановлено.")


def main():
    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    window = RedSandGUI()
    window.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
